---
title: "Weekly Bridge Report"
author: "David Bricker"
date: "12/8/2020"
output:
  html_document: default
  pdf_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(plotly)
library(readr)
library(openxlsx)
library(ggthemes)
library(RColorBrewer)
library(ggpubr)
library(scales)
library(reactable)
library(tinytex)
library(rmarkdown)
library(lubridate)

setwd("C:/Users/brick/desktop/Saga")

coalesce_by_column <- function(df) {
  return(coalesce(df[1], df[2]))
}

#summary_import <- function(download, team){
 # download <- paste0(download, '.xlsx')
  #df <- read.xlsx(download, sheetIndex = 1, colIndex = c(2:5,7:9)) %>% 
   #          pivot_wider(names_from = Parameter, values_from = Result)
  #df[,-(1:5)] <- apply(df[,-(1:5)],MARGIN = 2, function(x)as.numeric(x))
  #df[,-(1:5)] <- round(df[,-(1:5)],2)
  #df$Last.Name <- as.character(df$Last.Name)
  #df$Training.Load <- df$RPE * df$`Workout Duration`
  #assign('summary_df', df, envir = .GlobalEnv)
  #assign('summary_team', team, envir = .GlobalEnv)
#}

#summary_import('week_ind', 'allsum')

bridge_import <- function(download, team){ #DOWNLOAD = FILE NAME, TEAM = ODA NUMBER
  download <- paste0(download, '.xlsx')
  df <- read.xlsx(download, sheet = 1, cols = c(2:5,7:9),detectDates = TRUE,) %>% 
             pivot_wider(names_from = Parameter, values_from = Result)
  df[,-(1:5)] <- apply(df[,-(1:5)],MARGIN = 2, function(x)as.numeric(x))
  df$Last.Name <- as.character(df$Last.Name)
  df$Training.Load <- df$RPE * df$`Workout Duration`
  df <- df %>% 
    group_by(Last.Name, Date) %>% 
    summarise_all(coalesce_by_column)
  assign('bridge_df', df, envir = .GlobalEnv)
  assign('current_team', team, envir = .GlobalEnv)
}
bridge_import('bridge_week','Team 1')
```


## Weekly Report For Bridge Athletic Team: `r current_team`

```{r, message=FALSE, echo=FALSE}
reactable(bridge_df %>% 
            group_by(Last.Name) %>% 
            summarise('Post Workout Logs:' = sum(!is.na(`RPE`)),
                      'Average Session Length:' = round(mean(`Workout Duration`, na.rm = TRUE),0),
                      'Average Training Load:' = round(mean(Training.Load, na.rm = TRUE),0)),
          columns = list(
            Last.Name = colDef(footer = "Total/Average"),
            `Post Workout Logs:` = colDef(footer = function(values) sum(values)),
            `Average Session Length:` = colDef(footer = function(values) round(mean(values, na.rm = TRUE),2)),
            `Average Training Load:` = colDef(footer = function(values) round(mean(values, na.rm = TRUE),2))
          ),
          defaultColDef = colDef(footerStyle = list(fontWeight = "bold")))
```


## Distributions of performance log metrics.

```{r, warning=FALSE, echo=FALSE, fig.width=12, fig.height=8}
ggarrange(ggplot(bridge_df, aes(`Hours of Sleep`))+
            geom_histogram(fill = 'light blue',color = 'black', binwidth = 1, 
                           bins = 11)+
            scale_x_continuous(limits = c(1,10), breaks = 1:11)+
            scale_y_continuous(limits = c(0,20), breaks = seq(0,20,2))+
            labs(title = 'Hours of Sleep')+
            theme_bw()+
            theme(axis.title.x = element_blank(),
                  axis.text.x = element_text(size = 14),
                  axis.text.y = element_text(size = 14),
                  axis.title.y = element_text(size = 14)),
          
          ggplot(bridge_df, aes(`Quality of Sleep`)) +
            geom_histogram(fill = 'light blue', color = 'black', binwidth = 1, 
                           bins = 11)+
            scale_x_continuous(limits = c(1,10), breaks = 1:10)+
            scale_y_continuous(limits = c(0,20), breaks = seq(0,20,2))+
            labs(title = 'Quality of Sleep')+
            theme_bw()+
            theme(axis.title.x = element_blank(),
                  axis.text.x = element_text(size = 14),
                  axis.text.y = element_text(size = 14),
                  axis.title.y = element_blank()),
          
          ggplot(bridge_df, aes(`Nutrition`)) + 
            geom_histogram(fill = 'light blue', color = 'black', binwidth = 1, 
                           bins = 11)+
            scale_x_continuous(limits = c(1,10), breaks = 1:10)+
            scale_y_continuous(limits = c(0,20), breaks = seq(0,20,2))+
            labs(title = 'Nutrition')+
            theme_bw()+
            theme(axis.title.x = element_blank(),
                  axis.text.x = element_text(size = 14),
                  axis.text.y = element_text(size = 14),
                  axis.title.y = element_text(size = 14)),
          
          ggplot(bridge_df, aes(`Soreness`)) + 
            geom_histogram(fill = 'light blue', color = 'black', binwidth = 1, 
                           bins = 11)+
            scale_x_continuous(limits = c(1,10), breaks = 1:10)+
            scale_y_continuous(limits = c(0,20), breaks = seq(0,20,2))+
            labs(title = 'Soreness')+
            theme_bw()+
            theme(axis.title.x = element_blank(),
                  axis.text.x = element_text(size = 14),
                  axis.text.y = element_text(size = 14),
                  axis.title.y = element_blank()),
          
          nrow=2, ncol = 2)
```

## Daily performance log responses
```{r, echo=FALSE, warning=FALSE, message=FALSE, fig.width=12, fig.height=8}

ggarrange(
  ggplot(bridge_df, aes(Date, `Quality of Sleep`))+
  geom_rect(xmin = ymd(min(unique(bridge_df$Date))+1)-0.5,
            xmax = ymd(min(unique(bridge_df$Date))+1)+0.5,
            ymin = -Inf,
            ymax = Inf,
            fill = 'light gray')+
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+3)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+3)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+5)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+5)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_label(aes(label = Last.Name, fill = `Quality of Sleep`))+
  scale_fill_gradient(low = 'red', high = 'green')+
  scale_x_date(date_breaks = '1 day',limits = c(ymd(min(unique(bridge_df$Date))),ymd(min(unique(bridge_df$Date))+6)),
               expand = c(.08,.08))+
  scale_y_continuous(breaks = seq(1,10,1), limits = c(1,10))+
  guides(fill = FALSE)+
  labs(title = 'Quality of Sleep')+
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = -45, hjust = 0),
        axis.text = element_text(size = 12),
        axis.title.y = element_blank()),

          ggplot(bridge_df, aes(Date, `Nutrition`))+
  geom_rect(xmin = ymd(min(unique(bridge_df$Date))+1)-0.5,
            xmax = ymd(min(unique(bridge_df$Date))+1)+0.5,
            ymin = -Inf,
            ymax = Inf,
            fill = 'light gray')+
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+3)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+3)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+5)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+5)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_label(aes(label = Last.Name, fill = `Nutrition`))+
  scale_fill_gradient(low = 'red', high = 'green')+
  scale_x_date(date_breaks = '1 day',limits = c(ymd(min(unique(bridge_df$Date))),ymd(min(unique(bridge_df$Date))+6)),
               expand = c(.08,.08))+
  scale_y_continuous(breaks = seq(1,10,1), limits = c(1,10))+
  guides(fill = FALSE)+
  labs(title = 'Nutrition')+
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = -45, hjust = 0),
        axis.text = element_text(size = 12),
        axis.title.y = element_blank()),
  
          ggplot(bridge_df, aes(Date, `Stress`))+
  geom_rect(xmin = ymd(min(unique(bridge_df$Date))+1)-0.5,
            xmax = ymd(min(unique(bridge_df$Date))+1)+0.5,
            ymin = -Inf,
            ymax = Inf,
            fill = 'light gray')+
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+3)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+3)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+5)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+5)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_label(aes(label = Last.Name, fill = `Stress`))+
  scale_fill_gradient(low = 'red', high = 'green')+
  scale_x_date(date_breaks = '1 day',limits = c(ymd(min(unique(bridge_df$Date))),ymd(min(unique(bridge_df$Date))+6)),
               expand = c(.08,.08))+
  scale_y_continuous(breaks = seq(1,10,1), limits = c(1,10))+
  guides(fill = FALSE)+
  labs(title = 'Stress')+
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = -45, hjust = 0),
        axis.text = element_text(size = 12),
        axis.title.y = element_blank()),
  
          ggplot(bridge_df, aes(Date, `Soreness`))+
  geom_rect(xmin = ymd(min(unique(bridge_df$Date))+1)-0.5,
            xmax = ymd(min(unique(bridge_df$Date))+1)+0.5,
            ymin = -Inf,
            ymax = Inf,
            fill = 'light gray')+
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+3)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+3)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_rect(mapping = aes(xmin=ymd(min(unique(bridge_df$Date))+5)-0.5,
                          xmax = ymd(min(unique(bridge_df$Date))+5)+0.5,
                          ymin = -Inf,
                          ymax = Inf), fill = 'light gray') +
  geom_label(aes(label = Last.Name, fill = `Soreness`))+
  scale_fill_gradient(low = 'red', high = 'green')+
  scale_x_date(date_breaks = '1 day',limits = c(ymd(min(unique(bridge_df$Date))),ymd(min(unique(bridge_df$Date))+6)),
               expand = c(.08,.08))+
  scale_y_continuous(breaks = seq(1,10,1), limits = c(1,10))+
  guides(fill = FALSE)+
  labs(title = 'Soreness')+
  theme_bw()+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = -45, hjust = 0),
        axis.text = element_text(size = 12),
        axis.title.y = element_blank()),
          ncol = 2, nrow = 2)
```


## Daily training load. Team averages shown by bars. 
```{r, warning=FALSE, message=FALSE, echo=FALSE, fig.width=12, fig.height=8}
ggplot() +
  geom_col(data = bridge_df %>% 
             filter(Form.Name == 'Post Workout') %>% 
             group_by(Date) %>% 
             summarize('Average.Training.Load' = mean(Training.Load)),
           aes(Date, Average.Training.Load, fill = Average.Training.Load), color =
             'black') +
  scale_fill_gradient(low = 'green', high = 'red')+
  labs(title = 'Individual and Mean Training Load',
       y = 'Training Load (RPE*Duration)',
       x = 'Date')+
  geom_label(data = bridge_df , 
             aes(x = Date, y = Training.Load, label = Last.Name,
                 fill = Training.Load)) +
  scale_fill_gradient(low = 'green', high = 'red') +
  scale_x_date(date_breaks = "1 day",
               date_labels = '%m-%d') +
  guides(fill = FALSE) +
  theme_bw()+
  theme(axis.title.x = element_text(size = 14),
        axis.text.x = element_text(size = 14),
        axis.text.y = element_text(size = 14),
        axis.title.y = element_text(size = 14))
```



